Avoid using zero when season/episode information is not present
kodi-pvr/pvr.hts pull request #443
Opened 2020-03-10 13:16 UTC by jahutchi

The pvr.hts addon always sets the season number to 0, even when there is no season information available in Tvheadend. 

In Leia, this causes a display issue when the Tvheadend event or recording only has an Episode number but no Season number. As shown in these screenshots; kodi believes the Season Number is 0 and therefore treats this as a Special episode:

![screenshot1](https://user-images.githubusercontent.com/14977362/76315523-c1101e00-62d0-11ea-9bce-77175be684e4.png)

![screenshot2](https://user-images.githubusercontent.com/14977362/76315532-c66d6880-62d0-11ea-8a42-fbff1f79595d.png)

This is only a minor display issue. However, it will be made worse in Leia oweing to the following commit:

https://github.com/xbmc/xbmc/commit/3375a26606b3a6913bea18f4ef7b85a72b724915

This will mean that all Tvheadend events and recordings without any season/episode information in Tvheadend will always been shown as S0.

This can be easily resolved by initializing m_season and m_episode (for completeness) to -1.

2020-03-10 15:13 UTC, Jalle19 approved these changes
@ksooo

2020-03-10 17:44 UTC, ksooo requested changes
Please change season/episode members and setters/getters type to signed int and we should be good to go.

2020-03-10 17:44 UTC, ksooo commented on src/tvheadend/entity/Event.h
> +      m_episode(-1),
Those members are unsigned int, thus cannot carry signed values.

2020-03-10 17:44 UTC, ksooo commented on src/tvheadend/entity/Recording.h
> +      m_episode(-1),
Those members are unsigned int, thus cannot carry signed values.

2020-03-10 22:14 UTC, jahutchi commented
> Please change season/episode members and setters/getters type to signed int and we should be good to go.

Made a start but realised a few other variables needed adjusting...will take a look tomorrow.

2020-03-11 16:25 UTC, jahutchi commented
> 
> 
> > Please change season/episode members and setters/getters type to signed int and we should be good to go.
> 
> Made a start but realised a few other variables needed adjusting...will take a look tomorrow.

I think I've identified and adjusted all the getters and setters... now ready for a further review.

2020-03-11 17:42 UTC, ksooo approved these changes
Thank you.

2020-03-11 17:43 UTC, merged

2020-03-11 17:51 UTC, jahutchi commented
Are backports for Leia still being accepted? Will be happy to create a pull request if so?

2020-03-11 18:06 UTC, ksooo commented
Is Leia affected by this bug? I don't think so.

2020-03-11 18:07 UTC, ksooo commented
Ah, it is. So, go ahead and open a PR forLeia.