[Matrix] change to new C++ PVR interface way
kodi-pvr/pvr.hts pull request #455
Opened 2020-05-25 19:13 UTC by AlwinEsch

Changes related to xbmc/xbmc#16485.

This make the addon to the new C++ addon interface.
Runtime test was OK.
Only is in Kodi Matrix a bug with is channels icons and not shown, where is in Leia OK (not related to change here). On other addons they has worked, maybe with missing file extensions there?

2020-05-25 21:04 UTC, ksooo requested changes
Wow, good job. Minors only.

2020-05-25 21:04 UTC, ksooo commented on src/tvheadend/HTSPConnection.cpp
> +    m_client.ConnectionStateChange(serverString, newState, "");
Please do not keep the client instance at the connection as a member, instead extend the IHTSPConnectionListener interface with a method ConnectionStateChange and call it from here (m_connlistener->ConnectionStateChange(...)). CTvheadend already implements IHTSPConnectionListener, let it also implement the new method. Thus, we can keep the software design clean.

2020-05-25 21:04 UTC, ksooo commented on src/tvheadend/HTSPConnection.h
> +  kodi::addon::CInstancePVRClient& m_client;
No need for this member; see my other comment.

2020-05-25 21:04 UTC, ksooo commented on src/tvheadend/HTSPDemuxer.cpp
> +  return m_client.AllocateDemuxPacket(0);
I'd prever not to hold the client instance as a member here, but to use an interface for decoupling, like I did with IHTSPConnectionListener. Please create a new interface IDemuxPacketHandler, let CTVHeadend implement it and hold a ref to that listener as a member here.

2020-05-25 21:04 UTC, ksooo commented on src/tvheadend/HTSPDemuxer.cpp
> +    kodi::addon::PVRCodec codec = m_client.GetCodecByName("rds");
Same pattern here. Instaed of using the client instance directly, create an interface ICodecProvider, let CTvheadend implement it, keep a ref to that interface as member of this class.

2020-05-25 21:04 UTC, ksooo commented on src/tvheadend/HTSPDemuxer.h
> +  HTSPDemuxer(kodi::addon::CInstancePVRClient& client, HTSPConnection& conn);
No need for the client, but for refs to the two new interfaces I mentioned earlier.

2020-05-25 21:04 UTC, ksooo commented on src/tvheadend/HTSPDemuxer.h
> +  kodi::addon::CInstancePVRClient& m_client;
Replace this by refs to the two new interfaces I mentioned.

2020-06-10 20:49 UTC, AlwinEsch commented
@ksooo have updated the request.
On "IHTSPConnectionListener" is the "ConnectionState" function added where now in CTvheadend
About the demux I created the "IHTSPDemuxPacketHandler" and also now as parent on CTvheadend

Hope it is correct and match your wanted way.

2020-06-10 21:13 UTC, ksooo commented on src/tvheadend/IHTSPDemuxPacketHandler.h
> + * HTSP Connection Listener interface
HTSP Demux Packet Handler interface

2020-06-10 21:13 UTC, ksooo commented on src/tvheadend/IHTSPConnectionListener.h
> +  virtual void ConnectionState(const std::string& connectionString,
I would name this method `ConnectionStateChange`.

2020-06-11 10:17 UTC, AlwinEsch commented on src/tvheadend/IHTSPDemuxPacketHandler.h
> + * HTSP Connection Listener interface
Ups a c&p

2020-06-11 10:19 UTC, AlwinEsch commented on src/tvheadend/IHTSPConnectionListener.h
> +  virtual void ConnectionState(const std::string& connectionString,
Is renamed, was on begin not sure if same name and function on two parent classes not become conflict, but build and runtime test was OK.

2020-06-13 05:54 UTC, merged